'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Role_playing_dice_rolling_simulator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aged_Stone_Tiles_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aged Stone Tiles 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BrickFloor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BrickFloor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD10_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD10_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD10_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD10_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD10_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD10_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD10_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD10_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD10_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD10_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD10_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD10_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD10_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD10_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD10_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD10_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD10_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD10_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD10_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD10_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD12_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD12_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD20_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD20_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD3_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD3_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD3_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD3_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD3_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD3_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD4_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD4_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD4_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD4_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD4_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD4_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD4_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD4_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD4_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD4_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD6_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD6_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD6_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD6_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD6_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD6_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD6_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD6_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD6_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD6_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD6_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD6_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD8_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD8_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD8_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD8_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD8_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD8_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD8_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD8_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD8_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD8_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD8_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD8_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD8_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD8_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cD8_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cD8_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD10_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD10_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD10_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD10_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD10_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD10_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD10_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD10_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD10_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD10_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD10_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD10_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD10_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD10_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD10_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD10_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD10_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD10_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD10_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD10_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD12_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD12_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD20_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD20_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD3_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD3_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD3_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD3_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD3_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD3_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD4_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD4_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD4_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD4_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD4_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD4_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD4_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD4_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD4_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD4_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD6_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD6_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD6_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD6_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD6_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD6_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD6_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD6_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD6_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD6_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD6_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD6_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD8_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD8_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD8_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD8_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD8_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD8_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD8_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD8_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD8_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD8_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD8_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD8_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD8_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD8_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cfD8_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cfD8_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D10_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D10_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D10_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D10_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D10_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D10_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D10_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D10_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D10_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D10_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D10_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D10_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D10_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D10_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D10_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D10_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D10_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D10_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D10_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D10_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D12_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D12_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D20_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D20_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D3_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D3_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D3_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D3_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D3_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D3_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D4_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D4_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D4_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D4_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D4_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D4_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D4_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D4_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D4_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D4_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D6_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D6_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D6_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D6_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D6_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D6_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D6_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D6_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D6_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D6_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D6_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D6_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D8_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D8_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D8_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D8_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D8_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D8_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D8_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D8_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D8_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D8_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D8_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D8_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D8_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D8_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D8_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D8_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mji0eJV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mji0eJV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mountain_Castle_fantasy_38732839_1600_900() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mountain-Castle-fantasy-38732839-1600-900", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property p731401470_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p731401470-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
